<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TMZ-DPC-2178" failures="1" tests="2" name="runner.TestRunner" time="48.783" errors="0" timestamp="2023-11-23T14:32:31 IST" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="19.653"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="29.130">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.stepdefinition.AdminLoginStepDefinition.checks_the_name_in_inpatient(AdminLoginStepDefinition.java:280)
at âœ½.checks the name in Inpatient(file:///C:/MainPilotDeepak/Test/smartHospital/src/test/resources/Features/Inpatient.feature:31)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.TestRunner -->
